# Generated by Django 2.2.6 on 2019-10-23 16:01

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Catagory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='TV',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=350)),
                ('year', models.IntegerField()),
                ('tmdb_title', models.CharField(max_length=350)),
                ('overview', models.TextField(blank=True)),
                ('poster', models.ImageField(upload_to='', verbose_name='media/tv/%Y/%m/%d/')),
                ('backdrop', models.ImageField(upload_to='', verbose_name='media/tv/%Y/%m/%d/')),
                ('tmdb_id', models.IntegerField()),
                ('vote_average', models.DecimalField(decimal_places=1, default=0, max_digits=2)),
                ('vote_count', models.IntegerField(default=0)),
                ('views', models.IntegerField(default=0)),
                ('date', models.DateTimeField(default=datetime.datetime.now)),
                ('catagory', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='tv.Catagory')),
            ],
        ),
        migrations.CreateModel(
            name='Season',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('tv_season_name', models.CharField(max_length=350)),
                ('tv', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='tv.TV')),
            ],
        ),
        migrations.CreateModel(
            name='Episode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('file_path', models.CharField(max_length=500)),
                ('season', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='tv.Season')),
            ],
        ),
    ]
