# Generated by Django 2.2.6 on 2019-11-01 16:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Catagory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('date', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Channel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=350)),
                ('overview', models.TextField(blank=True)),
                ('popular', models.BooleanField(default=False)),
                ('poster', models.ImageField(upload_to='', verbose_name='media/liveTv/%Y/%m/%d/')),
                ('backdrop', models.ImageField(blank=True, upload_to='', verbose_name='media/liveTv/%Y/%m/%d/')),
                ('link_1', models.CharField(max_length=500)),
                ('link_2', models.CharField(max_length=500)),
                ('date', models.DateTimeField(auto_now=True)),
                ('caragory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='liveTV.Catagory')),
            ],
        ),
    ]
