# Generated by Django 2.2.6 on 2019-11-01 17:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('liveTV', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='channel',
            name='backdrop',
            field=models.ImageField(blank=True, upload_to='media/liveTv/%Y/%m/%d/'),
        ),
        migrations.RemoveField(
            model_name='channel',
            name='caragory',
        ),
        migrations.AddField(
            model_name='channel',
            name='caragory',
            field=models.ManyToManyField(to='liveTV.Catagory'),
        ),
        migrations.AlterField(
            model_name='channel',
            name='date',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='channel',
            name='link_2',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='channel',
            name='poster',
            field=models.ImageField(upload_to='media/liveTv/%Y/%m/%d/'),
        ),
    ]
