# Generated by Django 2.2.6 on 2019-11-01 17:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('liveTV', '0002_auto_20191101_2300'),
    ]

    operations = [
        # migrations.RenameModel(
        #     old_name='Catagory',
        #     new_name='Catagory',
        # ),
        # migrations.RenameField(
        #     model_name='channel',
        #     old_name='caragory',
        #     new_name='caragory',
        # ),
    ]
