# Generated by Django 2.2.6 on 2019-10-04 14:05

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Actors',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('birthday', models.DateField(blank=True)),
                ('gender', models.CharField(choices=[(0, 'Male'), (1, 'Female')], default=0, max_length=10)),
                ('place_of_birth', models.CharField(blank=True, max_length=100)),
                ('biography', models.TextField(blank=True)),
                ('profile_pic', models.ImageField(blank=True, upload_to='', verbose_name='actors/%Y/%m/%d/')),
                ('tmdb_id', models.IntegerField(blank=True)),
                ('imdb_id', models.CharField(blank=True, max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Collections',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tmdb_id', models.IntegerField()),
                ('name', models.CharField(max_length=250)),
                ('poster', models.ImageField(blank=True, upload_to='collections/%Y/%m/%d/')),
                ('backdrop', models.ImageField(blank=True, upload_to='collections/%Y/%m/%d/')),
            ],
        ),
        migrations.CreateModel(
            name='Genres',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('add_date', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Movie_Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('add_date', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Qualities',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20)),
                ('add_date', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Subtitle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(max_length=5)),
                ('sub_file', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Trailers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=15)),
                ('name', models.CharField(max_length=50)),
                ('site', models.CharField(max_length=15)),
                ('trailer_type', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Years',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(unique=True)),
                ('add_date', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Movies',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('tagline', models.CharField(blank=True, max_length=600)),
                ('overview', models.TextField(blank=True)),
                ('file_path', models.CharField(max_length=500)),
                ('file_size', models.DecimalField(blank=True, decimal_places=1, max_digits=3)),
                ('poster', models.ImageField(upload_to='movies/%Y/%m/%d/')),
                ('backdrop', models.ImageField(blank=True, upload_to='movies/%Y/%m/%d/')),
                ('img_1', models.ImageField(blank=True, upload_to='movies/%Y/%m/%d/')),
                ('img_2', models.ImageField(blank=True, upload_to='movies/%Y/%m/%d/')),
                ('img_3', models.ImageField(blank=True, upload_to='movies/%Y/%m/%d/')),
                ('img_4', models.ImageField(blank=True, upload_to='movies/%Y/%m/%d/')),
                ('tmdb_id', models.IntegerField(blank=True)),
                ('imdb_id', models.CharField(blank=True, max_length=10)),
                ('release_date', models.DateField(blank=True)),
                ('views', models.IntegerField()),
                ('is_pub', models.BooleanField(default=True)),
                ('add_date', models.DateTimeField(default=datetime.datetime.now)),
                ('actors', models.ManyToManyField(to='movie.Actors')),
                ('catagory', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='movie.Movie_Category')),
                ('collections', models.ManyToManyField(to='movie.Collections')),
                ('genres', models.ManyToManyField(to='movie.Genres')),
                ('quality', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='movie.Qualities')),
                ('subtitle', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='movie.Subtitle')),
                ('trailers', models.ManyToManyField(to='movie.Trailers')),
                ('year', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='movie.Years')),
            ],
        ),
    ]
