# Generated by Django 2.2.6 on 2019-10-04 14:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Actors',
            new_name='Actor',
        ),
        migrations.RenameModel(
            old_name='Collections',
            new_name='Collection',
        ),
        migrations.RenameModel(
            old_name='Genres',
            new_name='Genre',
        ),
        migrations.RenameModel(
            old_name='Movies',
            new_name='Movie',
        ),
        migrations.RenameModel(
            old_name='Qualities',
            new_name='Qualitie',
        ),
        migrations.RenameModel(
            old_name='Trailers',
            new_name='Trailer',
        ),
        migrations.RenameModel(
            old_name='Years',
            new_name='Year',
        ),
    ]
