# Generated by Django 2.2.6 on 2019-10-04 15:33

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0005_auto_20191004_2123'),
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('tagline', models.CharField(blank=True, max_length=600)),
                ('overview', models.TextField(blank=True)),
                ('file_path', models.CharField(max_length=500)),
                ('file_size', models.DecimalField(blank=True, decimal_places=1, max_digits=3)),
                ('subtitle', models.CharField(blank=True, max_length=50)),
                ('poster', models.ImageField(upload_to='movies/%Y/%m/%d/')),
                ('backdrop', models.ImageField(blank=True, upload_to='movies/%Y/%m/%d/')),
                ('img_1', models.ImageField(blank=True, upload_to='movies/%Y/%m/%d/')),
                ('img_2', models.ImageField(blank=True, upload_to='movies/%Y/%m/%d/')),
                ('img_3', models.ImageField(blank=True, upload_to='movies/%Y/%m/%d/')),
                ('img_4', models.ImageField(blank=True, upload_to='movies/%Y/%m/%d/')),
                ('tmdb_id', models.IntegerField(blank=True)),
                ('imdb_id', models.CharField(blank=True, max_length=10)),
                ('release_date', models.DateField(blank=True)),
                ('views', models.IntegerField()),
                ('is_pub', models.BooleanField(default=True)),
                ('add_date', models.DateTimeField(default=datetime.datetime.now)),
            ],
        ),
        migrations.RenameModel(
            old_name='Actors',
            new_name='Actor',
        ),
        migrations.RenameModel(
            old_name='Collections',
            new_name='Collection',
        ),
        migrations.RenameModel(
            old_name='Genres',
            new_name='Genre',
        ),
        migrations.RenameModel(
            old_name='Qualities',
            new_name='Qualitie',
        ),
        migrations.RenameModel(
            old_name='Trailers',
            new_name='Trailer',
        ),
        migrations.RenameModel(
            old_name='Years',
            new_name='Year',
        ),
        migrations.DeleteModel(
            name='Movies',
        ),
        migrations.DeleteModel(
            name='Subtitle',
        ),
        migrations.AddField(
            model_name='movie',
            name='actors',
            field=models.ManyToManyField(to='movie.Actor'),
        ),
        migrations.AddField(
            model_name='movie',
            name='catagory',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='movie.Movie_Category'),
        ),
        migrations.AddField(
            model_name='movie',
            name='collections',
            field=models.ManyToManyField(to='movie.Collection'),
        ),
        migrations.AddField(
            model_name='movie',
            name='genres',
            field=models.ManyToManyField(to='movie.Genre'),
        ),
        migrations.AddField(
            model_name='movie',
            name='quality',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='movie.Qualitie'),
        ),
        migrations.AddField(
            model_name='movie',
            name='trailers',
            field=models.ManyToManyField(to='movie.Trailer'),
        ),
        migrations.AddField(
            model_name='movie',
            name='year',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='movie.Year'),
        ),
    ]
