# Generated by Django 2.2.6 on 2019-10-04 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0006_auto_20191004_2133'),
    ]

    operations = [
        migrations.AddField(
            model_name='actor',
            name='add_date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='actor',
            name='profile_pic',
            field=models.ImageField(blank=True, upload_to='actors/%Y/%m/%d/'),
        ),
    ]
