# Generated by Django 2.2.6 on 2019-10-06 10:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0007_auto_20191004_2151'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actor',
            name='profile_pic',
            field=models.ImageField(blank=True, upload_to='media/actors/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='collection',
            name='backdrop',
            field=models.ImageField(blank=True, upload_to='media/collections/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='collection',
            name='poster',
            field=models.ImageField(blank=True, upload_to='media/collections/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='actors',
            field=models.ManyToManyField(blank=True, to='movie.Actor'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='collections',
            field=models.ManyToManyField(blank=True, to='movie.Collection'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='file_size',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=3),
        ),
        migrations.AlterField(
            model_name='movie',
            name='genres',
            field=models.ManyToManyField(blank=True, to='movie.Genre'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='img_1',
            field=models.ImageField(blank=True, upload_to='media/movies/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='img_2',
            field=models.ImageField(blank=True, upload_to='media/movies/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='img_3',
            field=models.ImageField(blank=True, upload_to='media/movies/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='img_4',
            field=models.ImageField(blank=True, upload_to='media/movies/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='poster',
            field=models.ImageField(upload_to='media/movies/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='quality',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='movie.Qualitie'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='trailers',
            field=models.ManyToManyField(blank=True, to='movie.Trailer'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='views',
            field=models.IntegerField(default=0),
        ),
    ]
