# Generated by Django 2.2.6 on 2019-10-07 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0008_auto_20191006_1650'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='backdrop',
            field=models.ImageField(upload_to='movies/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='poster',
            field=models.ImageField(blank=True, upload_to='media/movies/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='subtitle',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='qualitie',
            name='title',
            field=models.CharField(max_length=5),
        ),
    ]
