# Generated by Django 2.2.6 on 2019-10-16 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0010_auto_20191007_1151'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='imdb_title',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AlterField(
            model_name='movie',
            name='backdrop',
            field=models.ImageField(upload_to='media/movies/%Y/%m/%d/'),
        ),
    ]
