# Generated by Django 2.2.6 on 2019-10-16 15:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0012_auto_20191016_1912'),
    ]

    operations = [
        migrations.CreateModel(
            name='Movie_actor_name',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('character', models.CharField(max_length=250)),
                ('actor_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='movie.Actor')),
                ('movie_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='movie.Movie')),
            ],
        ),
    ]
