# Generated by Django 2.2.6 on 2019-10-16 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0013_movie_actor_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie_actor_name',
            name='cast_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
