# Generated by Django 2.2.6 on 2019-10-23 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0018_auto_20191018_0730'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='vote_average',
            field=models.DecimalField(blank=True, decimal_places=1, default=0, max_digits=2),
        ),
        migrations.AddField(
            model_name='movie',
            name='vote_count',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
