# Generated by Django 2.2.6 on 2019-11-02 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0019_auto_20191023_1533'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mojaloss',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tmdb_id', models.IntegerField()),
                ('title', models.CharField(max_length=350)),
                ('year', models.IntegerField()),
                ('path', models.CharField(max_length=700)),
            ],
        ),
    ]
