# Generated by Django 2.2.6 on 2019-11-02 16:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0020_mojaloss'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mojaloss',
            name='tmdb_id',
        ),
    ]
