# Generated by Django 2.2.6 on 2019-11-14 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0021_remove_mojaloss_tmdb_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='NeedToDownload',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=350)),
                ('year', models.IntegerField(blank=True)),
                ('url', models.CharField(max_length=700)),
                ('done', models.BooleanField(default=False)),
            ],
        ),
    ]
